### ISSUE TITLE
Feature: User can create a task

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a task in the kanban board

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create a task in the kanban board with 3 different levels of priority: todo, progress, and urgent.
User can add notes to the task for details

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/180847284-386f341d-477b-4406-9419-2beaf9b7943d.png)
![image](https://user-images.githubusercontent.com/96744088/180847314-999ea559-08c0-4a08-82ff-697d6a08b87c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to store task based on userId
- [x] Update `data.sql` to store task under correct userId

### ☁️ Server Tasks

- [x] Update `server/index.js` to store data from client to matching userId
- [x] create route 'POST' /api/tasks to store new task from client to matching userId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component in create-task.jsx component that matches with the wireframe.
- [x] create-task page should have button named 'Create Task'
- [x] Clicking on 'Create Task' will show form 
- [x] Clicking save in the form will save the task under current user with correct userId, then form will go away.
- [x] Update component to hide form when click on cancel or submit in the form.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
