### ISSUE TITLE
Feature: User can view a task

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a task

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After creating a task, user can view the task in the kanban board.
clicking submit button on the create task form will show newly created task in the kanban board.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/180848353-ed6ee64e-5559-49d6-b9c4-69b9e774eb7d.png)
![image](https://user-images.githubusercontent.com/96744088/180848418-9583dcfe-965f-49fa-a2e6-7b56c85c077f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to get tasks from database for rendering tasks
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to render saved tasks in database in the home page
- [x] Submitting a new form will render new task on top of the existing tasks

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
