### ISSUE TITLE
Feature: User can edit a task

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a task

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can edit the existing tasks by clicking three-dots icon in the task box.
After clicking submit, user can see the edited task right away in the kanban board.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/180848738-eb2081e2-5c3a-4357-9d64-a583492c36d9.png)
![image](https://user-images.githubusercontent.com/96744088/180848788-c001cb73-06cd-49e6-8d2e-40c2b7233488.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to have updated value from client.
- [x] After submission, the database should have updated values for each column if applicable.

### ☁️ Server Tasks

- [x] Update `server/index.js` to have 'PUT' method for the app to update values in the database.
- [x] create app.put() to update the values in the database
- [x] make sure updated values are applied to state props after submission
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for editing tasks
- [x] use fetch to request data updates in the edit component
- [x] change status text color based on task's status
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
