### ISSUE TITLE
Feature: User can delete a task

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a task

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a three-dots icon to delete a task.
After clicking on delete button, the task will be deleted from the kanban board.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/96744088/180850224-4cd5bdb9-8b8e-42da-a9fa-b5836eca83cc.png)
![image](https://user-images.githubusercontent.com/96744088/180850266-07e36ec2-563d-4b99-a6bd-d13c4e7240fd.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to delete the selected task with `taskId`

### ☁️ Server Tasks

- [x] Update `server/index.js` to have a `DELETE` method to delete the selected task in the database, by using the taskId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] create a delete button in task box
- [x] Update component to have handleDeleteTask method
- [x] Make a fetch request with the DELETE method to send the server a delete request, by selecting the correct taskId
- [x] Make sure that the selected task is deleted from the database and on the main page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
