### ISSUE TITLE
Feature: User can sign in / register

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in or sign up for an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a register button to create an account, or sign in to an existing account after register.
When user is signed in, user can see the saved kanban board if user has previously saved one.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/96744088/180850129-777bd07d-3170-4beb-9ce9-cd3b1687cf11.png)
![image](https://user-images.githubusercontent.com/96744088/180850076-f4c0ef27-b2bc-4866-9639-e9ea588b2a8b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Initial setup of schema.sql file to create tables in database

### ☁️ Server Tasks

- [x] Update `server/index.js` to create POST /api/auth/sign-up to create new user account
- [x] Update `server/index.js` to create POST /api/auth/sign-in for users to sign in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render sign-up page
- [x] Create a component to render sign-in page
- [x] clicking `sign up` button will switch view to sign up page, and clicking `sign in` button will switch view to sign in page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
