### ISSUE TITLE
Feature: User can sign out

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a navbar, click on sign out button, then log out of an account.
The page will be switched to the sign in page after logged out.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/180850539-1144066c-90f6-4ae4-89e3-1070951e8554.png)
![image](https://user-images.githubusercontent.com/96744088/180850475-13f3394c-c89d-4e2c-be9f-652863bc6e66.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update component to have a sign out feature after log in
- [x] Clicking sign out button will lead to log in page
- [x] Sign out will remove token from localStorage

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
